# Verwende ein Node.js-Image als Basis
FROM node:16-alpine

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere package.json und package-lock.json (falls vorhanden)
COPY package*.json ./

# Installiere die Abhängigkeiten
RUN npm install

# Kopiere den Rest der Anwendung ins Arbeitsverzeichnis
COPY . .

# Baue das React-Projekt (falls es noch nicht gebaut wurde)
RUN npm run dev

# Setze den Port, auf dem die App laufen soll
EXPOSE 5000

# Starte die App
CMD ["npm", "start"]