# Verwende ein Node.js-Image als Basis
FROM node:16-alpine

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere package.json und package-lock.json (falls vorhanden)
COPY package*.json ./

# Kopiere das expect-Skript ins Docker-Image
COPY bryntum_login.sh .

# Setze Ausführungsrechte für das Skript
RUN chmod +x /app/bryntum_login.sh

# Führe das Login-Skript aus, um den npm-Login zu automatisieren
RUN /app/bryntum_login.sh

# Kopiere den Rest der Anwendung ins Arbeitsverzeichnis
COPY . .

# Baue das React-Projekt
RUN npm run build

# Setze den Port, auf dem die App laufen soll
EXPOSE 5173

# Setze den Startbefehl für die Anwendung
CMD ["npm", "start"]
