# Verwende ein Node.js-Image als Basis
FROM node:16-alpine

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere package.json und package-lock.json (falls vorhanden)
COPY package*.json ./

# Setze das npm-Token aus einer Build-Argumenten oder Umgebungsvariablen
ARG BRYNTUM_TOKEN
ENV BRYNTUM_TOKEN=${BRYNTUM_TOKEN}

# Führe npm login aus, um das Token zu verwenden
RUN echo "//npm.bryntum.com/:_authToken=${BRYNTUM_TOKEN}" > ~/.npmrc && npm install

# Kopiere den Rest der Anwendung ins Arbeitsverzeichnis
COPY . .

# Baue das React-Projekt
RUN npm run build

# Setze den Port, auf dem die App laufen soll
EXPOSE 5173

# Setze den Startbefehl für die Anwendung
CMD ["npm", "start"]
